version: '3.8'
 
services:
  postgres:
    image: postgres:latest
    container_name: my_challenge
    environment:
      POSTGRES_USER: desafio03
      POSTGRES_PASSWORD: docker1234
      POSTGRES_DB: challenge_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
 
volumes:
  db_data:
 
 